### PR TITLE
Support sending loopback packets as if received on an adapter.

### PR DESCRIPTION
**Pull request by mmueller-projektantrieb**
Fixes nmap/nmap#1343

Adjustable with PacketSetLoopbackBehavior.
Info about changes: https://docs.microsoft.com/en-us/windows-hardware/drivers/network/looping-back-ndis-packets

### CODE REVIEW

**Comment by dmiller-nmap** [comment]
This is interesting. I'd like to hear from @hsluoyz about why the existing lines with `NDIS_SEND_FLAGS_CHECK_FOR_LOOPBACK` were commented out, just in case there was a conflict with the intended behavior. I don't see why this wouldn't be a good default.

As far as the implementation goes, I think extending `PacketSetLoopbackBehavior()` is problematic because the API is not really extensible: code that currently sets either `NPF_ENABLE_LOOPBACK` or `NPF_DISABLE_LOOPBACK` would clobber the existing setting because the values are not set bits; there's no way to enable both or disable capturing sent packets while enabling loopback. Instead, I think I will define a new Packet.DLL API function for extensible behavior switching using bitmasks. `PacketSetLoopbackBehavior()` will be rewritten to translate the existing behavior into a call to this new function. We will still be able to use the `BIOCISETLOBBEH` IoControl code, too, avoiding problems with older Packet.dll (though the IoControl interface is not guaranteed to be backwards compatible).

**Comment by dmiller-nmap** [comment]
Well, now I've looked into it more I think that there is tremendous confusion over how to handle packets in several situations, because of the difference in architecture between WinPcap (NDIS 5 Protocol driver) and Npcap (NDIS 6 Filter driver). [This answer on StackExchange](https://stackoverflow.com/a/18478725/1183387), copied from and email from @jtippet, is mostly focused on packet filters, but it does a great job of explaining the Windows network stack and the differences between the two driver types, as well as the general idea of loopback behavior.

I think we will be able to accommodate all needs using the existing interface (`PacketSetLoopbackBehavior()` with only 2 settings) by adding the loopback check to outgoing packets without needing a way to turn this off. There are only a limited number of packet sources and destinations that we need to handle, so I will enumerate those and test them to ensure behavior as close to WinPcap as possible.

**Comment by hsluoyz** [comment]
Hi @dmiller-nmap , I think commenting `NDIS_SEND_FLAGS_CHECK_FOR_LOOPBACK` happens in porting NDIS 6 protocol driver to NDIS 6 filter driver: https://github.com/nmap/npcap/commit/5c9ef8156a0853882f53e968690724f79b7acbac#diff-bcc2b528a7ef2a7c2539b50b73f45d99R210

It's too far away but maybe I commented at that time because enabling that flag for a filter drive will cause duplicated packets received. As the docs: https://docs.microsoft.com/en-us/windows-hardware/drivers/network/looping-back-ndis-packets pointed by @mmueller-projektantrieb, this flag is the 3rd condition that makes Windows loopbacks the packets.

I think we can keep this commented line for safe. Or further, we can uncomment it and see what happens like if any duplicated packets there.

**Comment by rbeex** [comment]
Hi together. I hope all of you are healty! Is there anything we can do regarding this issue?

**Comment by dmiller-nmap** [comment]
@rbeex This PR has been very helpful in understanding the issue. We are currently in final implementation phase of a change that incorporates the `NDIS_SEND_FLAGS_CHECK_FOR_LOOPBACK` flag as well as streamlines Npcap's internal capturing of injected packets. When it is complete, our goal is to preserve the same API semantics as WinPcap, so code which currently expects injected traffic to be received by a protocol driver will not require any changes.

**Comment by dmiller-nmap** [comment]
An equivalent change was just released in Npcap 0.9990. Please test and leave feedback in nmap/nmap#1343 or open a new issue if you find it unsatisfactory.

The default behavior is to loop back injected packets, but we recommend that your code explicitly call `PacketSetLoopbackBehavior(PACKET_ENABLE_LOOPBACK)` in case this default is changed in the future.

**Comment by rbeex** [comment]
Hello daniel, here our feedback. It works well, thank you!

**Pull request closed without merging**
