### PR TITLE
Add VS temp file to ignore list

### PR DESCRIPTION
**Pull request by gbloice**

### CODE REVIEW

**Comment by hsluoyz** [comment]
Thanks for the first PR of Npcap!

**Comment by gbloice** [comment]
On 08/02/2016 07:11, hsluoyz wrote:
>
> Thanks for the first PR of Npcap!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nmap/npcap/pull/1#issuecomment-181232699>.
>
Standby, lots more incoming

**Comment by hsluoyz** [comment]
BTW, do you know how to upgrade WDK 10 from 10240 to 10586?

I have downloaded and installed the latest WDK 10 10586, but the include directories of npf project still point to 10240's files:

Here is my settings of ``npf Property Pages -> VC Directories -> Include Directories -> Evaluated value``

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\PlatformSDK\include
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\winrt
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\Include\um
```

I want to change the above 10240 to 10586, I googled many but still don't know how.

**Comment by gbloice** [comment]
Hi Hang,

Right click the solution in the Solution Explorer tab and select
"Retarget Solution".

If there are any absolute paths in the project properties then they also
have to be fixed.

I have such a change form a few days ago ready to send as a PR.

Note you have to update the SDK & WDK installs at the same time, the WDK
doesn't like different versions.

**Pull request merged**
